* GridFire

GridFire is a raster-based fire behavior model that may be used to
simulate the spread of wildland fires across a landscape, either
individually or in monte carlo simulations over space and time. For
inputs, it requires a stack of co-registered raster maps for your area
of interest as well as a text configuration file that specifies
various parameters necessary for the simulation.

* Usage

GridFire has been coded as a literate program
(https://en.wikipedia.org/wiki/Literate_programming) using Emacs'
org-mode (http://orgmode.org/worg/org-contrib/babel/). Full
documentation of the current system can always be found in the *org*
directory within this repository:

- org/GridFire.org :: Literate Program Source Code
- org/GridFire.pdf :: Woven Documentation

All source code files within this repository are generated directly
from *org/GridFire.org*.

* Contact
** Authors

- Gary W. Johnson, Ph.D.
- David S. Saah, Ph.D.
- Max Moritz, Ph.D.
- Kenneth Cheung

** Emails

- gjohnson@sig-gis.com
- dsaah@sig-gis.com
- mmoritz@sig-gis.com
- kcheung@sig-gis.com

* License

Copyright © 2014-2022 Spatial Informatics Group, LLC.

GridFire is distributed by Spatial Informatics Group, LLC. under the
terms of the Eclipse Public License version 2.0 (EPLv2). See
LICENSE.txt in this directory for more information.
